Tayfur.Blog.Mvc/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tayfur.Blog.Mvc.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tayfur.Blog.Mvc/Controllers/ArticleController.cs
using FluentValidation.Results;
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Tayfur.Blog.Service.Abstract;
using Tayfur.Blog.Service.ValidationRules.FluentValidation;
using Tayfur.Blog.Service.ViewModels;

namespace Tayfur.Blog.Mvc.Controllers
{
    /// <summary>
    /// This class manages the articles of the application.
    /// </summary>
    [Authorize]
    public class ArticleController : Controller
    {
        //private readonly BlogContext db = new BlogContext();

        private readonly IArticleService articleService;
        private readonly ICategoryService categoryService;
        public ArticleController(IArticleService articleService, ICategoryService categoryService)
        {
            this.articleService = articleService;
            this.categoryService = categoryService;
        }
        // GET: Article
        public ActionResult Index()
        {
            //var articles = db.Articles.Include(a => a.Category).Include(a=>a.Admin).OrderByDescending(x=>x.CreatedDate).Take(10);
            //return View(await articles.ToListAsync());
            return View(articleService.GetArticlesWithCategoryAndAdmin());
        }
   

        // GET: Article/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleCategoryAdminViewModel article = articleService.GetArtWithCatAdmWithId(id ?? default(Guid));
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(categoryService.GetCategories(), "Id", "CategoryName");
            return View();
        }

        // POST: Article/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryId,Title,Context")] ArticleViewModel article)
        {
            ArticleValidator articleValidator = new ArticleValidator();
            ValidationResult results = articleValidator.Validate(article);
            if (results.IsValid)
            {
                article.Id = Guid.NewGuid();
                article.CreatedDate = DateTime.Now;
                article.CreatedBy = Guid.Parse(User.Identity.Name);
                article.IsDeleted = false;

                bool result = articleService.AddArticle(article);

                if (result)
                {
                    return RedirectToAction("Index");
                }
            }
            if (!results.IsValid)
            {
                foreach (var error in results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);

                }
            }
            ViewBag.CategoryId = new SelectList(categoryService.GetCategories(), "Id", "CategoryName");
            return View(article);
        }

        // GET: Article/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleViewModel article = articleService.GetArticle(id??default(Guid));
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(categoryService.GetCategories(), "Id", "CategoryName", article.CategoryId);
            return View(article);
        }

        // POST: Article/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryId,Title,Context,CreatedDate,ModifiedBy,ModifiedDate,CreatedBy,IsDeleted")] ArticleViewModel article)
        {
            ArticleValidator articleValidator = new ArticleValidator();
            ValidationResult results = articleValidator.Validate(article);
            if (results.IsValid)
            {
                article.ModifiedDate = DateTime.Now;
                if (Session["UserId"] != null)
                {
                    article.ModifiedBy = Guid.Parse(User.Identity.Name);
                }

                bool result = articleService.UpdateArticle(article);
                if (result)
                {
                    return RedirectToAction("Index");
                }
            }
            if (!results.IsValid)
            {
                foreach (var error in results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }
            ViewBag.CategoryId = new SelectList(categoryService.GetCategories(), "Id", "CategoryName", article.CategoryId);
            return View(article);
        }

        // GET: Article/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleCategoryAdminViewModel article = articleService.GetArtWithCatAdmWithId(id ?? default(Guid));
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ArticleViewModel article = articleService.GetArticle(id);
            articleService.DeleteArticle(article);
            return RedirectToAction("Index");
        }
    }
}

Tayfur.Blog.Mvc/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tayfur.Blog.Service.Abstract;
using Tayfur.Blog.Service.ViewModels;
using Tayfur.Blog.Service.ValidationRules.FluentValidation;
using FluentValidation.Results;

namespace Tayfur.Blog.Mvc.Controllers
{
    /// <summary>
    /// This class manages the categories of the application.
    /// </summary>
    [Authorize]
    public class CategoryController : Controller
    {
        //private BlogContext db = new BlogContext();

        private readonly ICategoryService categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        // GET: Category
        public ActionResult Index()
        {
            //return View(await db.Categories.Include(a=>a.Admin).ToListAsync());
            return View(categoryService.GetCategories());
        }

        // GET: Category/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryViewModel category = categoryService.GetCategory(id ?? default(Guid));
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryName,Description")] CategoryViewModel category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(category);

            if (results.IsValid)
            {
                category.Id = Guid.NewGuid();
                category.CreatedDate = DateTime.Now;
                category.CreatedBy = Guid.Parse(User.Identity.Name);
                category.IsDeleted = false;

                bool result = categoryService.AddCategory(category);
                if (result)
                {
                    return RedirectToAction("Index");
                }
            }
            if (!results.IsValid)
            {
                foreach (var error in results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);

                }
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryViewModel category = categoryService.GetCategory(id ?? default(Guid));
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryName,Description,CreatedDate,ModifiedBy,ModifiedDate,CreatedBy,IsDeleted")] CategoryViewModel category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(category);
            if (results.IsValid)
            {
                category.ModifiedDate = DateTime.Now;
                if (Session["UserId"] != null)
                {
                    category.ModifiedBy = Guid.Parse(User.Identity.Name);
                }

                bool result = categoryService.UpdateCategory(category);
                if (result)
                {
                    return RedirectToAction("Index");
                }
            }
            if (!results.IsValid)
            {
                foreach (var error in results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);

                }
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CategoryViewModel category = categoryService.GetCategory(id??default(Guid));
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            CategoryViewModel category = categoryService.GetCategory(id);
            categoryService.DeleteCategory(category);
            return RedirectToAction("Index");
        }
    }
}

Tayfur.Blog.Mvc/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.tiny.cloud/1/zt55uy8uocqa8cw0i3hn472fxu6d374p5tm41dib1t1zsz6z/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/Home/Index">My Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item m-lg-2">
                            <a class="nav-link" aria-current="page" href="/Admin/Index">Admin Dashboard</a>
                        </li>
                        <li class="nav-item m-lg-2">
                            <a class="nav-link" href="/Article/Index">Makaleleri Yönet</a>
                        </li>
                        <li class="nav-item m-lg-2">
                            <a class="nav-link" href="/Category/Index">Kategorileri Yönet</a>
                        </li>
                        <li class="nav-item dropdown m-lg-2">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @User.Identity.Name
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    @Html.ActionLink("Kullanıcı Görünümü", "Index", "Home", null, new { @class = "dropdown-item" })
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    @Html.ActionLink("Çıkış Yap", "LogOut", "Account", null, new { @class = "dropdown-item" })
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container mt-3">
        @RenderBody()
    </div>
    <script src="~/Scripts/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript">

        const currentLocation = location.href;
        const menuItem = document.querySelectorAll('a');
        const menuLength = menuItem.length;
        for (let i = 0; i < menuLength; i++) {
            if (menuItem[i].href === currentLocation) {
                menuItem[i].className = "nav-link active"
            }
        }

        tinymce.init({
            selector: 'textarea#editor',
            menubar: false,
            branding: false,
            width: 800,
            height: 300,
            plugins: [
                'advlist autolink link image lists charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'table emoticons template paste help'
            ],
            toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist outdent indent | link image | print preview media fullpage | ' +
                'forecolor backcolor emoticons | help',
        });
                //$(document).ready(function () {
                //    $("ul.navbar-nav li").on('click', function () {
                //        $("ul.navbar-nav li").removeClass('active');
                //        $("ul.navbar-nav li").on('click', function () {
                //            $("li a").addClass('active');
                //        })
                //});
    </script>

</body>
</html>

Tayfur.Blog.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - Tayfur Blog</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="/Home/Index">Tayfur Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Home/Index">Ana Sayfa</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Home/About">Hakkımda</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Home/Contact">İletişim</a></li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Account/Login">Yönetici Girişi</a></li>
                    }
                    else
                    {
                        <li class="nav-item dropdown mt-3">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @User.Identity.Name
                                @*@Session["UserName"].ToString();*@
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>@Html.ActionLink("Makale Yönetimi", "Index", "Article", null, new { @class = "dropdown-item" })</li>
                                <li>
                                    @Html.ActionLink("Kategori Yönetimi", "Index", "Category", null, new { @class = "dropdown-item" })
                                </li>
                                <li>
                                    @Html.ActionLink("Yönetici İşlemleri", "Index", "Admin", null, new { @class = "dropdown-item" })
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    @Html.ActionLink("Çıkış Yap", "LogOut", "Account", null, new { @class = "dropdown-item" })
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderSection("pageHeader", false)
    </div>
    <div>
        @RenderBody()
    </div>

    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://www.hackerrank.com/tayfur"  target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-hackerrank fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/in/tayfurerkenci/"  target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-linkedin-in fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/tayfurerkenci" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Tayfur Blog 2021</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Scripts/scripts.js"></script>
</body>
</html>